### ISSUE TITLE
Improving the angle quotes / guillemets

### ISSUE THREAD

**Issue by clemensg** [EbenSorkin/Merriweather#10]
Hi,

would it be possible to reduce the spacing of the two arrows in the Guillemet symbols / Angle quotes / French quotation marks (« and ») a little bit in the Merriweather font?
I really like the type, with that little exception: The inner spacing of the two arrows in the angle quotes is too wide for my taste when using it as french/swiss quotation marks. They look more like two < symbols clumped together and not like Guillemets.

@EbenSorkin Was that a conscious decision to make the spacing that large and would you be willing to reduce it a tiny bit? Would be really great!

Besides that little nitpick, awesome work!

Cheers,
Clemens

**Comment by EbenSorkin** [comment]
I am really happy to hear this kind of feedback and will incorporate it into a new edition.

I tried to balance out the needs of the screen vs what is conventional in Merriweather so there is a lot of stuff where things get big including spaces between shapes to help with rendering.

That said, there has been a ton of change with regard to the way Merriweather is used ( in print sometimes ) and the screens that have become much more capable. There are compelling reasons to rethink the design.

In the meantime I would be happy to send you your own adjusted set of files if you are willing to give me feedback.

I am about to move house so this can’t be done immediately. Would you think about if you are willing to do this and contact me in a week or so?

Thanks very much!

-e.

**Comment by clemensg** [comment]
Hi,

thanks for the fast response. Of course, that sounds great!
I could show it to my coworker (he is the typographer who criticised the spacing within the angle brackets as I used the font on a website) and send you his feedback. I am just the engineer.

Sure, we are in no rush. If you send the updated font to clemensgru@gmail.com, we'll take a look and give you feedback!
I'll send you a message in one or two weeks, if I don't hear anything.

**Comment by clemensg** [comment]
Hi,

just a quick reminder. Two weeks ago you said I should contact you again about the Merriweather font.

The Guillemot symbols / Angle quotes  (« and ») are the only characters we are not happy with.
How much do you think you can reduce the inner spacing of each angle quote?

If you have a draft, just send it to me and we will have a look! :)

Cheers,
Clemens

**Comment by clemensg** [comment]
*ping* :)

**Comment by EbenSorkin** [comment]
How is this?

Old



New


It may be more useful to see it a text set. Shall I make a PDF for you?

What about the reverse?



Note: these are not kerned.

-e.

**Comment by davelab6** [comment]
@EbenSorkin arg, the github system seems to not process html/markdown when the message was created by email. Did you resolve this in the latest v1.582 version?

**Comment by clemensg** [comment]
Hi Eben, sorry for not replying earlier.

I was thinking about guillemets like here on the left (à la française) https://cdnfrancecopywriter-francecopywriter.netdna-ssl.com/wp-content/uploads/2014/02/guillemets1.jpg

They should not be just two combined angle characters but have a specific shape.

What do you think about those in the image on the left side?

Thanks.

> Am 29.10.2015 um 17:37 schrieb Eben Sorkin <notifications@github.com>:
> 
> How is this?
> 
> Old
> 
> 
> 
> New
> 
> 
> It may be more useful to see it a text set. Shall I make a PDF for you?
> 
> What about the reverse?
> 
> 
> 
> Note: these are not kerned.
> 
> -e.
>

**Comment by davelab6** [comment]
@EbenSorkin I must admit that, in comparing the Old and New images above, the change is very subtle. I think based on @clemensg 's image today, they must become about half as wide.

**Comment by adrientetar** [comment]
You may try tightening it some more, but not too much. Change is subtle but as with kerning, that kind of distance can be enough to go from "it's off" to "it's okay".

> They should not be just two combined angle characters but have a specific shape.

They're almost always the same shape. How many fonts do you know have different shapes?

**Comment by davelab6** [comment]
@adrientetar In suggesting they become 50% narrower, am thinking more of the comment

> They look more like two < symbols clumped together and not like Guillemets.

**Comment by clemensg** [comment]
@adrientetar I meant they should not be just two < symbols clumped together (<<), but the shape of the Guillemets should be thicker in the middle and thinner at the outside, as seen in the image I posted above. I did not mean that the two elements of the Guillemets symbol should be different, I meant that they should be different from <<. And not just by the distance but also by the shape.

I also agree with @davelab6 that the change in distance is too subtle.

Maybe @EbenSorkin can find a trade-off which makes us all happy :)

**Comment by clemensg** [comment]
@EbenSorkin Hi Eben, what's the status on this?
What do you think about the shape of the Guillemets from the picture https://cdnfrancecopywriter-francecopywriter.netdna-ssl.com/wp-content/uploads/2014/02/guillemets1.jpg ?
I especially like the wide angle and the fact that the line thickness decreases from thick at the vertical center to slim at the upper and lower end.
At the moment, the only characters I'm not happy with in Merriweather are the Guillemets.. ;)

**Comment by adrientetar** [comment]
Yeah but Merriweather is a low contrast family with generous horizontal proportions; the image you show comes from like Times New Roman so obviously Merriweather cannot have the same design.

That being said guillemets should definitely be tightened and I think the Yrsa font (which is a fork of Merriweather) is a good reference for how it should be.

**Comment by sergeevabc** [comment]
Russian user here. Current outlook of Merriweather guillemets « » is definitively unbearable.
They should be tightened, correct approach could be found in [Charis][1], [Lora][2], [PT Serif][3]

[1]: http://software.sil.org/charis/
[2]: https://github.com/cyrealtype/Lora-Cyrillic/
[3]: http://www.paratype.com/public/

**Comment by EbenSorkin** [comment]
Thanks! I ‘ll add that to my to do list.

-e.

**Comment by EbenSorkin** [comment]
This is done in the last push to GIT

**Comment by sergeevabc** [comment]
Merriweather is so… dense. Its 16/1.7 is roughly equals 18/1.5 of [Rosalind Serif][1] or Georgia.

[1]: https://github.com/researchgate/rosalind-serif

**Comment by davelab6** [comment]
It was designed to be highly readable on phones, tablets and PC's 6-7 years
ago, so yes, it may be a design of it's time in some ways. I expect when it
has a Variable Font version similar to Amstelvar you will be able to get
what you want out of it
