### ISSUE TITLE
Light non-italic appears as separate font family

### ISSUE THREAD

**Issue by dpk** [EbenSorkin/Merriweather#12]
![](https://i.imgur.com/JuywGGo.png)

**Comment by EbenSorkin** [comment]
What OS?
What app?
Where did the fonts come from Google, or Fontsquirrel or Github?

-e.

**Comment by dpk** [comment]
OS X. System-wide font list (shown in Font Book, but reflected in all apps).

Direct from this repo.

**Comment by malvese** [comment]
:+1: The version here on Github as well as the one on Fontsquirrel.

**Comment by davelab6** [comment]
I'll take care of this now

**Comment by davelab6** [comment]
@dpk @malvese please try the latest version, v1.582, you can download it from www.google.com/fonts

**Comment by malvese** [comment]
@davelab6 It's indeed fixed, thanks. Merriweather Light now behaves nicely :)

![merrilight](https://cloud.githubusercontent.com/assets/193492/12529908/6c7880a8-c1cb-11e5-86a3-d537f0d69824.png)

**Comment by davelab6** [comment]
Please close
