### ISSUE TITLE
Merriweather ST no longer available

### ISSUE THREAD

**Issue by dpk** [EbenSorkin/Merriweather#13]
It appears the service that sold Merriweather ST is gone from the entire interweb. http://www.webink.com/

Where can it be obtained now?

**Comment by mjmasn** [comment]
+1 I'm also looking for the ST version

**Comment by nickswalker** [comment]
+1 Would like to know

**Comment by EbenSorkin** [comment]
There will be a series of newer ST versions at some point in the next year that are optical specific e.g there will be a Caption Text and Display instead of a one size fits all which is what exists today.

**Comment by EbenSorkin** [comment]
They are here: https://github.com/SorkinType/Merriweather

**Comment by davelab6** [comment]
There's ideally wouldn't be 2 repos, but I won't have time to help with
this for about a month. I'll send you a calendar invite now, Eben.

**Comment by dpk** [comment]
Closing this since the original question has basically been answered. If there are Google Fonts issues, perhaps that belongs in a separate issue.
