### ISSUE TITLE
Merriweather-Light.ufo minor issues

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#14]
- [ ] Merriweather-Light.ufo is missing the `Scedilla` and `scedilla` chars:

<img width="1509" alt="screen shot 2016-01-22 at 00 27 40" src="https://cloud.githubusercontent.com/assets/261579/12503600/97771194-c0a3-11e5-8ca2-846c4690d1b5.png">

For example, here they are in the Bold

<img width="1509" alt="screen shot 2016-01-22 at 00 28 11" src="https://cloud.githubusercontent.com/assets/261579/12503599/9772bc70-c0a3-11e5-8307-4d811574a7fb.png">

Once they are added a new `locl` line 17 should be inserted as follows:

```
sub [Scedilla scedilla] by [Scommaaccent scommaaccent];
```
- [x] ~~Merriweather-Light.ufo is missing the `f_i_trk` glyph.~~

~~Once it is added, a new line 13 should be added to `liga` with~~

```
sub f i by f_i_trk;
```

Update: The above is no longer needed since with v1.583+ the trk glyphs are removed from all styles

**Comment by davelab6** [comment]
@lemzwerg says, 

> I've found a slight error in the `name` table's description string of `Merriweather-Light` version 1.584: It contains a 0xA0  character between `for` and `editorial` instead of a plain space. Additionally, you should replace the word `Renissance` with `Renaissance` in all `name` tables.

**Comment by EbenSorkin** [comment]
This is fixed in the new push to GIT
