### ISSUE TITLE
Review cap accents

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#21]
It would be good to review all the cap accents for a future release, as some seem a little too low

<img width="1656" alt="screen shot 2016-01-24 at 23 23 56" src="https://cloud.githubusercontent.com/assets/261579/12542464/8dba99e6-c2f1-11e5-9cb3-d16454718862.png">

**Comment by EbenSorkin** [comment]
Because we resolved not to increase vertical space in the design so as not to impact existing users, we are some what constrained in what's possible here. However the acute dieresis etc could be moved up. The grave and acute etc can only be adjusted a little

**Comment by EbenSorkin** [comment]
These are adjust din the new edition. We can reopen this if the adjustment isn't enough.

**Comment by davelab6** [comment]
Okay cool - the latest vertical metrics strategy we use means that you don't have any restrictions any more, compared to 7 years ago when the first vertical metrics strategy was decided. @m4rc1e note that this will be an expected change.

**Comment by EbenSorkin** [comment]
Are you saying that we can avoid clipping now in *web browsers* without
worry ( even if we can't assume the same in other environments) and so we
should allow diacritics to be taller? And that this can be done before we
make a Variable font edition?

-e.

**Comment by davelab6** [comment]
Yes; I'm not sure where would now see clipping.

https://github.com/googlefonts/gf-docs/blob/master/VerticalMetrics.md has
all the details.
