### ISSUE TITLE
Review glyph sets to ensure they are equal across the family

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#24]
The regular has more glyphs than any other style, 729.

**Comment by davelab6** [comment]
The cyrillic is also uneven across styles:

Merriweather-Regular.ttf cyrillic 101/101 100%
Merriweather-Regular.ttf cyrillic-ext 130/333 39%
Merriweather-Black.ttf cyrillic 101/101 100%
Merriweather-Black.ttf cyrillic-ext 130/333 39%
Merriweather-BlackItalic.ttf cyrillic 101/101 100%
Merriweather-BlackItalic.ttf cyrillic-ext 126/333 37%
Merriweather-Bold.ttf cyrillic 101/101 100%
Merriweather-Bold.ttf cyrillic-ext 130/333 39%
Merriweather-BoldItalic.ttf cyrillic 101/101 100%
Merriweather-BoldItalic.ttf cyrillic-ext 126/333 37%
Merriweather-Italic.ttf cyrillic 101/101 100%
Merriweather-Italic.ttf cyrillic-ext 126/333 37%
Merriweather-Light.ttf cyrillic 101/101 100%
Merriweather-Light.ttf cyrillic-ext 130/333 39%
Merriweather-LightItalic.ttf cyrillic 101/101 100%
Merriweather-LightItalic.ttf cyrillic-ext 126/333 37%
Merriweather-Regular.ttf cyrillic 101/101 100%
Merriweather-Regular.ttf cyrillic-ext 130/333 39%

**Comment by EbenSorkin** [comment]
Done

**Comment by davelab6** [comment]
Great!
