### ISSUE TITLE
Merriweather Sans: the hyphen is placed too high

### ISSUE THREAD

**Issue by Charlie-Harper** [EbenSorkin/Merriweather#35]
The hyphen issue refered in this post https://ebensorkin.wordpress.com/download-merriweather/#comment-458 remains in the sans variant. Please, fix it! 

Merriweather Sans is my default font in KDE desktop. (Yes! Love the oldstyle figures!)
Merriweather and Merriweather Sans are my default fonts in Firefox.
Merriweather is my default font for LibreOffice documents.

**Comment by davelab6** [comment]
@EbenSorkin maybe you can take care of this in December?

**Comment by EbenSorkin** [comment]
This should be fixed in all styles in the most recent push.

**Comment by davelab6** [comment]
Awesome!

**Comment by Charlie-Harper** [comment]
Good news. Merriweather is one of the rare free fonts with oldstyle figures. When and where will it be available?

**Comment by davelab6** [comment]
@Charlie-Harper an update on Google Fonts is coming soon, and a further update with all 4 numeral styles will be published later this year or early next year (with the lining tabular figures as defaults)

**Comment by EbenSorkin** [comment]
So that's a no to 5 styles of full size figures? hybrid as default + 4?

-e.

**Comment by davelab6** [comment]
I think we should only every have 4 styles. Hybrid as default may be ok for text faces like this...

**Comment by Charlie-Harper** [comment]
I would prefer that the default numeral style be the distinctive proportional oldstyle figures.

**Comment by davelab6** [comment]
I appreciate your feedback
