### ISSUE TITLE
vertical metrics

### ISSUE THREAD

**Issue by m4rc1e** [EbenSorkin/Merriweather#36]
Looks like the vertical metrics have changed a lot. I recommend we revert these back.

left: git version, right: fonts on fonts.google.com
![screen shot 2016-12-13 at 10 50 14](https://cloud.githubusercontent.com/assets/7525512/21135414/19db7f42-c122-11e6-99ab-241a79efa3c0.png)

@davelab6 @alexeiva

**Comment by EbenSorkin** [comment]
I like the vertical spacing on the left better but agree that changing it
on people who have designed their sites with the other on in mind will be
disruptive. I Should add that if we are adding support for let's say
vietnamese we would need to change the vertical metrics. Probably whatever
change we make should be based on the that set of needs. That should also
make Czech user's happier with the default spacing too. Maybe the change I
see was done to prepare for that? How did it happen?

Best!

-e.

**Comment by m4rc1e** [comment]
Hey Eben,

We had a mega discussion around 4 months ago on this topic. The agreed solution seemed to be a [solution](https://groups.google.com/d/msg/googlefonts-discuss/W4PHxnLk3JY/MpyLLY4jAwAJ) proposed by Khaled Hoseny. 

> The above setup will mean that by default Vietnamese line spacing will 
> be too tight and users of Vietnamese text will need to explicitly set 
> CSS line spacing to a better value. This is not ideal, but it is a 
> better trade-off IMO than scaling down the accents. 

I suggest we revert back to the old metrics and update the win ascent and win descent to avoid clipping. I am more than happy to roll this out.

Cheers,
Marc

**Comment by alexeiva** [comment]
>  How did it happen?

In the git version I have set v metrics by the 125% rule for happy Vietnamese. 

<img width="1022" alt="screen shot 2016-12-16 at 12 07 36 pm" src="https://cloud.githubusercontent.com/assets/16634089/21260867/4b0ef00e-c388-11e6-9368-4a2aff24ca5d.png">

**Comment by davelab6** [comment]
That is weird because the version on gf is relatively new, being updated
about a year ago

**Comment by m4rc1e** [comment]
@alexeiva there's no such thing as happy Vietnamese vertical metrics. Referring to my quote above again.

> > We had a mega discussion around 4 months ago on this topic. The agreed solution seemed to be a solution proposed by Khaled Hoseny.
> > 
>  > The above setup will mean that by default Vietnamese line spacing will
>  > be too tight and users of Vietnamese text will need to explicitly set
>  > CSS line spacing to a better value. This is not ideal, but it is a
> > better trade-off IMO than scaling down the accents.

**Comment by m4rc1e** [comment]
@EbenSorkin I'm more than happy to opt for either solution. 

I personally prefer the new spacing but I always consider legacy issues as well. At the end of the day, it is your call. 

Once you have made a decision, I'll submit a pr.

Cheers,
Marc

**Comment by m4rc1e** [comment]
@ping @EbenSorkin

**Comment by EbenSorkin** [comment]
Sorry this has taken so long. I really like the new v metrics and I can see
that it really is helpful for Cyrillic as well.

I do 100% agree k it needs to changed. I would have made it bigger than it
is but at the time we made it that wasn't functional in the browsers yet.
Thank goodness that changed.

I think I would like to ask for something slightly less linespace than the
example if we can not clip vietnamese doing it.
I have a few reasons.

1) It will break fewer existing layouts if the change is less.
2) For English use the line space feel slightly excessive.

Also I think it would be good to make sure that the heights used are
consistent across weights. So to that end I think we should also look at
the Black.

Does it make best sense for me to suggest this compromise height?

-e.

**Comment by m4rc1e** [comment]
What about halfway between the two?

![screen shot 2017-01-11 at 10 38 24](https://cloud.githubusercontent.com/assets/7525512/21845331/21b710e4-d7ea-11e6-92a6-9ba8b3b61e80.png)

Left is 50% between new version and fonts.google.com version. Right is current version hosted on fonts.google.com

Imo, optically, this looks spot on.

**Comment by davelab6** [comment]
Actually I am a bit wary of changing the line height Metrics at all.... the
idea of khaleds technique is that the line height will not change and still
nothing gets clipped.

On Jan 11, 2017 5:39 AM, "Marc Foley" <notifications@github.com> wrote:

What about halfway between the two?

[image: screen shot 2017-01-11 at 10 38 24]
<https://cloud.githubusercontent.com/assets/7525512/21845331/21b710e4-d7ea-11e6-92a6-9ba8b3b61e80.png>

Left is 50% between new version and fonts.google.com version. Right is
current version hosted on fonts.google.com

Imo, optically, this looks spot on.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EbenSorkin/Merriweather/issues/36#issuecomment-271835838>,
or mute the thread

**Comment by m4rc1e** [comment]
@davelab6 I've got this scripted [now](https://github.com/m4rc1e/mf-glyphs-scripts/commit/80f55151b3844929a0e571d89dd00b7cfd29240e)

@EbenSorkin The approach Dave is mentioning, was used in our GF update. We retain the same proportions as the legacy metrics. However, there is no clipping in Window's applications. We found this to be the safest solution. Shall we proceed with this approach?

**Comment by EbenSorkin** [comment]
I really like the way that halfway looks. But Dave’ suggestions does seem like the safest thing in terms of disrupting users.

I must have missed where Khaled’s technique is mentioned. Where is that? Are there any side effects? For instance does this work really well for browsers but not work so well elsewhere? Does it create different linespacing in different OS’?

-e.

**Comment by m4rc1e** [comment]
@EbenSorkin here https://groups.google.com/forum/#!msg/googlefonts-discuss/W4PHxnLk3JY/MpyLLY4jAwAJ

This approach will not cause any problems on any platforms. The values will change but the vertical metrics will visually appear the same. 

I recently did this approach for [Overpass](https://github.com/RedHatBrand/Overpass/issues/37).
