### ISSUE TITLE
ff followed by i become ligature in italic 400

### ISSUE THREAD

**Issue by John-B** [EbenSorkin/Merriweather#39]
Where 'ff' is followed by 'i', and the font is set to italics using `<em>` or `<i>` tags, the ff becomes a ligature. This affects only the 400 and 700 italic versions of the font, as a try-out on the Google font page shows (https://fonts.google.com/specimen/Merriweather). It does not affect the 300 and 900 italic versions. It cannot be disabled by disabling ligatures in css. I assume this is bug rather than an undocumented feature?

**Comment by jonnysooter** [comment]
Also experiencing this issue. 
![screen shot 2017-02-01 at 2 35 45 pm](https://cloud.githubusercontent.com/assets/1653474/22529369/06f76a26-e88c-11e6-9c49-095f681fffd2.png)

**Comment by davelab6** [comment]
Thanks for reporting this! I'll get it fixed asap

**Comment by m4rc1e** [comment]
![screen shot 2017-02-02 at 06 45 24](https://cloud.githubusercontent.com/assets/7525512/22539648/3c6555ec-e913-11e6-8a0c-96c2d4aa4cbc.png)

Confirmed. I'll do this now. We have tests in place to catch this in the future. Sorry for the inconvenience.

**Comment by John-B** [comment]
Many thanks :-)
