### ISSUE TITLE
Is it possible to make the digits aligned to the baseline?

### ISSUE THREAD

**Issue by iliyang** [EbenSorkin/Merriweather#4]
Let me start by saying that I love Merriweather and I think it's great that it's free!

My only issue with the font is that the digits are not vertically aligned with the baseline (like in Georgia), which does not look great in scientific documents. Is there a way to make them aligned with the baseline (like in Times New Roman) ?

Thanks!

**Comment by EbenSorkin** [comment]
The only solution at this time is to buy a license for the ST version which has the number feature.

The ST version will be available to license fairly soon.

-e.

**Comment by iliyang** [comment]
Thanks for the prompt reply!

I was thinking of somehow modifying the sources by shifting the digits up. Is this approach feasible?

**Comment by EbenSorkin** [comment]
You could try that but the shapes won’t fit quite right.

Also, if you do try that the license requires that you change the name.

A license isn’t that expensive! And the St versions has other cool things about it too like proper superiors and inferiors, automatic fractions, more symbols and so on.

-e.

**Comment by iliyang** [comment]
I have no problem with buying a license, however I wanted a webfont that I can distribute with a web app to other people and make it public at some point. And this probably goes against the license.

By the way, I wonder if it would be possible to include webfonts in this repository. I used [FontSquirrel](http://www.fontsquirrel.com/tools/webfont-generator) to convert the TTF files I found here to webfonts, and the result renders much better than [Google Font's version](https://www.google.com/fonts/specimen/Merriweather) on my "low-DPI" monitor, especially smaller font sizes.

**Comment by EbenSorkin** [comment]
On Apr 11, 2015, at 9:36 AM, Iliyan Georgiev <notifications@github.com> wrote:

> I have no problem with buying a license, however I wanted a webfont that I can distribute with a web app to other people and make it public at some point. And this probably goes against the license.
> 
> 

You could get a license with an addendum for that. It could work. 

> By the way, I wonder if it would be possible to include webfonts in this repository. I used FontSquirrel to convert the TTF files I found here to webfonts, and the result renders much better than Google Font's version on my "low-DPI" monitor, especially smaller font sizes.
> 
> 
That’s because Google still has not loaded the new stuff and Font Squirrel has! There is a big jump in quality. The Pro ST family is a similar jump but in capability.

**Comment by davelab6** [comment]
I think this is tricky to change in the main default version, because changing from the "old style" numbers to "lining" numbers would look very different for all the existing users.

Its possible to support different number styles via OpenType, and with the upcoming Safari 9.1 (desktop) 9.2 (mobile) release then OpenType features will work everywhere (given the latest versions of browsers) 

So it could be good to fund this in the libre version later this year

**Comment by EbenSorkin** [comment]
Lining figures are being added. Note! The current release is for testing only. There are still numerous bugs.

**Comment by EbenSorkin** [comment]
Lining figures (but not tabular lining figures) have been added. I look at tabular ones and other figure styles for a next edition.

**Comment by davelab6** [comment]
That sounds good; I want to standarize the whole GF collection on lining tabular figures as defaults, and have all 4 sets of numbers, in all text families :)

**Comment by EbenSorkin** [comment]
Merriweather's digits are sort of modeled after Georgia's which use a
hybrid not old style not lining style. We could support all 4  ( Old style,
Old style tabular and lining and Lining tabular) and still keep these as a
default. But if you want to move the existing figure to the old style
position we could do that. However I worry that some users won't like the
effect in text.
