### ISSUE TITLE
Differing glyph sets between Roman and Italic weights

### ISSUE THREAD

**Issue by m4rc1e** [EbenSorkin/Merriweather#41]
The Italic and Roman glyph sets don't match.

Here's a list of glyphs which are in either the Roman or the Italic but not both:

sheqel
zero.slash
softsign-cy.loclBGR
twothirds
bullet.cap
ydotaccent
en-cy.loclBGR
uni03BC
i.uc
exclamdouble
Ydotaccent
leftRightArrow
shcha-cy.loclBGR
sha-cy.loclBGR
eight.dnom
mu
komizje-cy
seven.numr
pe-cy.loclBGR
oneeighth
exclamdbl
Gacute
Scedilla
uni00AD
guillemotright
Komidje-cy
ndotaccent
four.dnom
Gmacron
commaturnedabovecomb
Ndotaccent
Delta
tse-cy.loclBGR
guillemetleft
f_i_trk
dram-arm
acaron
Oslashacute
Komizje-cy
caroncomb.alt
Gcaron
seveneighths
napostrophe
two.dnom
iishort-cy.loclBGR
Aringacute
uni03A9
oslashacute
threeeighths
four.numr
komidje-cy
three.dnom
guillemotleft
ge-cy.loclBGR
fiveeighths
uni0394
tail-cy.case
guillemetright
softhyphen
periodcentered.cap
tail-cy
Omega
aringacute
five.numr
upDownArrow
I.uc
scedilla
iigrave-cy.loclBGR
ii-cy.loclBGR
f_f_i_dflt
hardsign-cy.loclBGR

I've done some further digging around and notice that many of these exist in the old .ufo and vfb sources. I'm guessing this was a porting issue.

**Comment by alexeiva** [comment]
minus the 11 `.loclBGR` glyphs — these are stylistical differences between Bulgarian roman and italic styles.

**Comment by alexeiva** [comment]
These Komi glyphs are obsolete. I suggest removing them whatsoever

```
komizje-cy
Komidje-cy
Komizje-cy
komidje-cy
```

These glyphs shall be set non-exportable, their use is for dev purposes only. Fine if they don't match across weights
``
tail-cy.case
tail-cy
```

Othere non-Cyrillic glyphs need to be renamed to glyphs naming convention. This will resolve a lot of duplicate issues. 

```
.cap > .case
uni03BC = mu 
```

**Comment by m4rc1e** [comment]
Ok as @alexeiva suggested about the Bulgarian, the list is:
sheqel
zero.slash
twothirds
bullet.cap
ydotaccent
uni03BC
i.uc
exclamdouble
Ydotaccent
leftRightArrow
eight.dnom
mu
komizje-cy
seven.numr
oneeighth
exclamdbl
Gacute
Scedilla
uni00AD
guillemotright
Komidje-cy
ndotaccent
four.dnom
Gmacron
commaturnedabovecomb
Ndotaccent
Delta
guillemetleft
f_i_trk
dram-arm
acaron
Oslashacute
Komizje-cy
caroncomb.alt
Gcaron
seveneighths
napostrophe
two.dnom
Aringacute
uni03A9
oslashacute
threeeighths
four.numr
komidje-cy
three.dnom
guillemotleft
fiveeighths
uni0394
tail-cy.case
guillemetright
softhyphen
periodcentered.cap
tail-cy
Omega
aringacute
five.numr
upDownArrow
I.uc
scedilla
f_f_i_dflt

**Comment by alexeiva** [comment]
No | name | nice name
---|---|---
1 | acaron | acaron
2 | Aringacute | Aringacute
3 | aringacute | aringacute
4 | bullet.cap | bullet.cap
5 | caroncomb.alt | caroncomb.alt
6 | commaturnedabovecomb | commaturnedabovecomb
7 | Delta | Delta
8 | dram-arm | dram-arm
9 | eight.dnom | eight.dnom
10 | exclamdbl | exclamdouble
11 | exclamdouble | exclamdouble
12 | f_f_i_dflt | f_f_i_dflt
13 | f_i_trk | f_i_trk
14 | five.numr | five.numr
15 | fiveeighths | fiveeighths
16 | four.dnom | four.dnom
17 | four.numr | four.numr
18 | Gacute | Gacute
19 | Gcaron | Gcaron
20 | Gmacron | Gmacron
21 | guillemetleft | guillemetleft
22 | guillemetright | guillemetright
23 | guillemotleft | guillemetleft
24 | guillemotright | guillemetright
25 | i.uc | i.uc
26 | I.uc | I.uc
27 | Komidje-cy | Komidje-cy
28 | komidje-cy | komidje-cy
29 | komizje-cy | komizje-cy
30 | Komizje-cy | Komizje-cy
31 | leftRightArrow | leftRightArrow
32 | mu | mu
33 | napostrophe | napostrophe
34 | ndotaccent | ndotaccent
35 | Ndotaccent | Ndotaccent
36 | Omega | Omega
37 | oneeighth | oneeighth
38 | Oslashacute | Oslashacute
39 | oslashacute | oslashacute
40 | periodcentered.cap | periodcentered.cap
41 | Scedilla | Scedilla
42 | scedilla | scedilla
43 | seven.numr | seven.numr
44 | seveneighths | seveneighths
45 | sheqel | sheqel
46 | softhyphen | softhyphen
47 | tail-cy | tail-cy
48 | tail-cy.case | tail-cy.case
49 | three.dnom | three.dnom
50 | threeeighths | threeeighths
51 | two.dnom | two.dnom
52 | twothirds | twothirds
53 | uni00AD | softhyphen
54 | uni0394 | Delta
55 | uni03A9 | Omega
56 | uni03BC | mu
57 | upDownArrow | upDownArrow
58 | ydotaccent | ydotaccent
59 | Ydotaccent | Ydotaccent
60 | zero.slash | zero.slash

There are seven duplicates in this list
```
Delta
exclamdouble
guillemetleft
guillemetright
mu
Omega
softhyphen
```

**Comment by EbenSorkin** [comment]
This is fixed now.
