### ISSUE TITLE
Include Gawker Media's '?' as an alt

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#42]
I request the Gawker question mark to be available as a stylistic alternate in an upcoming release of Merriweather :)

**Comment by nickswalker** [comment]
Do you mean the [interrobang](https://en.wikipedia.org/wiki/Interrobang)?

**Comment by EbenSorkin** [comment]
I think he means the actual question mark. Gawker Media made their own and some other changes as well.

-e.

**Comment by EbenSorkin** [comment]
I altered the ? to be less odd. I have not worked out how to do alts in Glyphs yet. That could be a part of the next edition. There could be 2-3 other things like quotes or a letter or two if that seems useful.

**Comment by davelab6** [comment]
Its documented here, https://glyphsapp.com/tutorials/stylistic-sets and in the 'automatic' section of https://glyphsapp.com/tutorials/features-part-1-simple-substitutions (which links to the handbook PDF)

**Comment by EbenSorkin** [comment]
Is it the case that you would like to let The sites that use The
merriweather derived "Elizabeth" use this version instead?

**Comment by davelab6** [comment]
Yes that would be cool if it can happen

**Comment by EbenSorkin** [comment]
In that case I'd like to mod their shapes slightly so that they don't stick
out quite as much maybe. Up close at least they are quite a mismatch.

**Comment by davelab6** [comment]
Sounds good!

**Comment by EbenSorkin** [comment]
Question marks and Quotes from Elizabeth have been added as Alternatives via stylistic set (ss.01) to Merriweather. Because they had very inefficient number points I refined them and made their weight match the masters more precisely.

**Comment by davelab6** [comment]
Also the `$`?

**Comment by davelab6** [comment]
Please could you post a triple comparison, of default/before/after? :)

**Comment by EbenSorkin** [comment]
I didn't notice the $. I'll attend to that now and then show all 3 versions
of each glyph

**Comment by EbenSorkin** [comment]
Added it.

-e.
