### ISSUE TITLE
Failures on Firefox Developer Edition

### ISSUE THREAD

**Issue by archSeer** [EbenSorkin/Merriweather#44]
Hi, not sure if this is the best place to report, but using this font via Google Fonts will make it fail in Firefox Dev Edition:

```
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:106:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:106:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:106:12
downloadable font: rejected by sanitizer (font-family: "Merriweather" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/ZvcMqxEwPfh2qDWBPxn6nkZRWJQ0UjzR2Uv6RollX_g.woff2  css:106:12
downloadable font: Layout: DFLT script doesn't satisfy the spec. DefaultLangSys is NULL (font-family: "Merriweather" style:italic weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/EYh7Vl4ywhowqULgRdYwIB0ue0Sk5cwvYx5tGiUAApw.woff2  css:138:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "Merriweather" style:italic weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/EYh7Vl4ywhowqULgRdYwIB0ue0Sk5cwvYx5tGiUAApw.woff2  css:138:12
downloadable font: GSUB: Failed to parse script list table (font-family: "Merriweather" style:italic weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/EYh7Vl4ywhowqULgRdYwIB0ue0Sk5cwvYx5tGiUAApw.woff2  css:138:12
downloadable font: rejected by sanitizer (font-family: "Merriweather" style:italic weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/merriweather/v15/EYh7Vl4ywhowqULgRdYwIB0ue0Sk5cwvYx5tGiUAApw.woff2
```

It seemed to have worked just fine until recently (a few weeks ago).

**Comment by archSeer** [comment]
Related issue 

https://github.com/webcompat/web-bugs/issues/4742#issuecomment-284063386

**Comment by EbenSorkin** [comment]
I am sorry I missed this when it came in. I think it will be 1-2 days
before I can look into it seriously.

But in the meantime would yo explain what gstatic is? Is that a local
server that's serving downloaded Merriweather? If so where did it come from
Google or another source?

-e.

**Comment by archSeer** [comment]
It's a google cache server I think! I'm including the font directly through Google Fonts, and that's where google is serving it from:

If you check this generated stylesheet, [fonts.googleapis.com/css?subset=latin,latin-ext&family=Merriweather:300,400,700,300italic,400italic](//fonts.googleapis.com/css?subset=latin,latin-ext&family=Merriweather:300,400,700,300italic,400italic), you can see it's using the same hosts.

Based on that other thread, apparently the issue is that the FF developer edition is stricter about the OTF format.


Anyway thank you so much for the Merriweather font family! I've been extensively using it; it's the main font on my personal site among other things.

**Comment by sheharyarn** [comment]
Bump. Really hoping this gets resolved soon. I opened a [similar thread here](Layout: DFLT script doesn't satisfy the spec).

And thank you for the awesome font!

**Comment by EbenSorkin** [comment]
I have sent the errors to Google. I do know they made a rollback that
probably is the source and which broke some Cyrillc too. I am hoping they
will have a fix to the whole thing soon. I'll try to get them on text chat
today to see what they are planning to do an when.

-e.

**Comment by davelab6** [comment]
This was partly a problem with the OpenType spec, which was fixed, and the OTS was updated; and partly a problem with fontTools, which was fixed, and the GF API was updated with it; so this should not happen (and was never a problem in the fonts.)

**Comment by davelab6** [comment]
Test page, looks good to me: https://output.jsbin.com/hubepuz/

<img width="1920" alt="screen shot 2017-10-27 at 22 15 55" src="https://user-images.githubusercontent.com/261579/32130324-7c626c60-bb64-11e7-812b-94540dd15458.png">
