### ISSUE TITLE
Fractional px sizes rendering poorly in Windows

### ISSUE THREAD

**Issue by maya** [EbenSorkin/Merriweather#46]
There are some issues with fractional sizes in Windows, see: https://github.com/18F/federalist/issues/1124 

@EbenSorkin do you have any idea what's happening / if this can be resolved?

**Comment by EbenSorkin** [comment]
I'll see if the new auto hint solved this. The previous edition was about 2-3 years ago and I suspect the new will be much better.

**Comment by maya** [comment]
@EbenSorkin Glad to hear! Do you have a link to the new version?

The version we're using on the U.S. Web Design Standards is 2 years old. If you could point us to the files we should use, it would be greatly appreciated. Pull requests welcome too: https://github.com/18F/web-design-standards/tree/develop/src/fonts

**Comment by EbenSorkin** [comment]
You can collect the files from here

https://github.com/EbenSorkin/Merriweather

And will be a formal release that reflects the changes here
https://github.com/EbenSorkin/Merriweather/releases

But that isn't done yet.

We made a call for bugs to be reported in the current version. I think when
we feel all is clear the release will be made.

Would it be useful to have a .zip file with the current TTFs?

-e.

**Comment by EbenSorkin** [comment]
Also I think it will make better sense to have a pull request for your GT
after the formal release is made.

-e.

**Comment by maya** [comment]
Sounds good, we will wait to update until the release. Do you have an ETA of when that will be?

>Would it be useful to have a .zip file with the current TTFs?

What would that be used for? The primary benefit of including it?

**Comment by EbenSorkin** [comment]
RE: ETA - not my decision but I have a sense it might be in 1-2 weeks.

REL TTF files - I could send you these ( or you can go to the GIT and grab
them) if you wanted to test the current version and make sure it works for
your application.

-e.

**Comment by maya** [comment]
Hi @EbenSorkin, did the release you mentioned get made? Is it this: https://github.com/EbenSorkin/Merriweather/releases/tag/v2.001?

**Comment by EbenSorkin** [comment]
No. That's not the one. The new source format is in the app Glyphs.

It's here. https://github.com/EbenSorkin/Merriweather/tree/master/fonts

There are quite a lot of improvements for language support especially
cyrillic and eastern european languages in addition to improved full height
numbers options.

I am sending these in part to encourage you to forward any remaining
requests from Gov/Fed users.

I am expecting an additional publishing push in Jan and would like to
include those at that time.

I am planning
- with a completing all small numbers for inferiors and superiors and
fractions
-  better French and Vietnamese support. We support both French and
Vietnamese now but in a way can be improved on quite a lot.

Merriweather may become a variable font as well. We did a successful mini
experiment with just the roman in Nov. But with the new Fontlab out I may
be going back to that to make the Variable version! :-P

Best!

-e.

**Comment by davelab6** [comment]
There was a v2.002 added to Google Fons (in
https://github.com/google/fonts/pull/1293) which you can download from
http://fonts.google.com/download?family=Merriweather

**Comment by maya** [comment]
Thanks for the update @EbenSorkin and info @davelab6. One thing that a government designer mentioned was the lack of tabular figures, which seemed to be released in the paid version (no longer there?) at the time.

**Comment by EbenSorkin** [comment]
The newest one has lining but not yet tabular figures. Tabular figures are
coming soon.

-e.
