### ISSUE TITLE
Glyph issues

### ISSUE THREAD

**Issue by m4rc1e** [EbenSorkin/Merriweather#47]
Using [GF Regression](http://45.55.138.144/), I've found the following:

**Regular**
![screen shot 2017-10-26 at 10 17 54](https://user-images.githubusercontent.com/7525512/32044972-f9a830d0-ba36-11e7-9595-873a91d511a8.png)

**Light Italic**
![screen shot 2017-10-26 at 10 06 23](https://user-images.githubusercontent.com/7525512/32044420-6cf01d2a-ba35-11e7-8747-a968165a6f6c.png)

![screen shot 2017-10-26 at 10 07 42](https://user-images.githubusercontent.com/7525512/32044465-8768bf40-ba35-11e7-9d96-5b2b31bd16cf.png)

![screen shot 2017-10-26 at 10 07 33](https://user-images.githubusercontent.com/7525512/32044468-898d56dc-ba35-11e7-8d6f-bf59e802a478.png)

![screen shot 2017-10-26 at 10 08 19](https://user-images.githubusercontent.com/7525512/32044507-a8cc1718-ba35-11e7-8efc-a1d30b6ac584.png)

![screen shot 2017-10-26 at 10 08 13](https://user-images.githubusercontent.com/7525512/32044508-a8e29c04-ba35-11e7-8c39-03a197767511.png)

![screen shot 2017-10-26 at 10 09 24](https://user-images.githubusercontent.com/7525512/32044547-c3380f30-ba35-11e7-91f9-060447eb3d94.png)

**Light**
![screen shot 2017-10-26 at 10 09 51](https://user-images.githubusercontent.com/7525512/32044603-ed066226-ba35-11e7-912f-36f166f72e36.png)

![screen shot 2017-10-26 at 10 10 55](https://user-images.githubusercontent.com/7525512/32044622-fd96557e-ba35-11e7-911f-2460abe4eb27.png)

**Italic**
![screen shot 2017-10-26 at 10 12 00](https://user-images.githubusercontent.com/7525512/32044687-22507624-ba36-11e7-8b08-6a2ce35497b8.png)

**BoldItalic**
![screen shot 2017-10-26 at 10 12 34](https://user-images.githubusercontent.com/7525512/32044743-50df9420-ba36-11e7-84be-c503a4ce87a7.png)

**Bold**
![screen shot 2017-10-26 at 10 14 16](https://user-images.githubusercontent.com/7525512/32044791-723d3e2e-ba36-11e7-9a16-7a731dffbd02.png)

**Black**
![screen shot 2017-10-26 at 10 20 58](https://user-images.githubusercontent.com/7525512/32045135-695f8950-ba37-11e7-9998-7cd71a9cbd94.png)

**Black Italic**
![screen shot 2017-10-26 at 10 20 10](https://user-images.githubusercontent.com/7525512/32045086-45f9c656-ba37-11e7-94c9-5558c2a1632d.png)

![screen shot 2017-10-26 at 10 14 45](https://user-images.githubusercontent.com/7525512/32044811-8261dd0a-ba36-11e7-969c-dfce89fad89f.png)

![screen shot 2017-10-26 at 10 15 21](https://user-images.githubusercontent.com/7525512/32044844-9821e6b2-ba36-11e7-932f-b98e121faa64.png)

![screen shot 2017-10-26 at 10 15 39](https://user-images.githubusercontent.com/7525512/32044860-a42a62fe-ba36-11e7-8f56-d107d0b1ead4.png)

**Comment by EbenSorkin** [comment]
These are now fixed.
