### ISSUE TITLE
Why is the `f_f_i_dflt` without a tittle?

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#48]
I am curious, why is the `f_f_i_dflt` without a tittle?

<img width="1165" alt="screen shot 2017-10-27 at 22 29 36" src="https://user-images.githubusercontent.com/261579/32130430-5ed4a972-bb66-11e7-90fb-8172bc4204e7.png">

<img width="1116" alt="screen shot 2017-10-27 at 22 29 46" src="https://user-images.githubusercontent.com/261579/32130431-5edf16a0-bb66-11e7-89f3-19604a0d536a.png">

**Comment by EbenSorkin** [comment]
This was made in anticipation of Turkish specific OT code and is for small caps if I recall correctly. It could be eliminated for now.

**Comment by davelab6** [comment]
Following up on #14 (and #17) I see that the trk glyphs are now back in Roman and Italic, and #43 is fixed, so I checked the features mentioned there... The ROM and MOL rule is there:

    sub [Scedilla scedilla] by [Scommaaccent scommaaccent];

<img width="1920" alt="screen shot 2017-10-27 at 22 34 41" src="https://user-images.githubusercontent.com/261579/32130494-7524dc8c-bb67-11e7-9018-aed647dda510.png">
<img width="1920" alt="screen shot 2017-10-27 at 22 34 28" src="https://user-images.githubusercontent.com/261579/32130495-752eb0d6-bb67-11e7-90c0-95ab9a43fc9f.png">


But now that the `f_i_trk` glyph is added, a new rule is needed for it, I think. https://glyphsapp.com/tutorials/localize-your-font-turkish says 

> 1. First, make sure you have `idotless` and `dotaccentcomb` in your font ... 

You have both of these in roman and italic

> Now, create the glyphs `Idotaccent` and especially `idotaccent`

You have both of these in roman and italic, too.

Then it says,

> If Glyphs finds `idotaccent` in your font, it can automatically create the respective entries in your `locl` feature. These will substitute `i` by `idotaccent` for Turkish (TRK), Kazakh (KAZ), Tatar (TAT), Crimean Tatar (CRT) and Azeri (AZE).

I do see all them in the above :)

Then for ligatures, the article says,

> Or, thirdly, introduce separate f_idotaccent and f_f_idotaccent ligatures. That’d be really cool.

I guess that is what you have in your `f_i_trk` except you named it differently that way. 

But whereas in #13 I said, 

>> Once it is added, a new line 13 should be added to liga with
>>
>> `sub f i by f_i_trk;`

then I **guess** you would need to customize the locl feature to add rules for all the language the i is replaced with, like this...

```
language KAZ;
sub f idotaccent by f_i_trk;
language TAT;
sub f idotaccent by f_i_trk;
language TRK;
sub f idotaccent by f_i_trk;
language CRT;
sub f idotaccent by f_i_trk;
language AZE;
sub f idotaccent by f_i_trk;
```

But I just guessed at this. Would need to be confirmed.... @m4rc1e what do you think?

**Comment by EbenSorkin** [comment]
That's all correct I think. And the doubling of the ligature may have to do
with supporting small caps. Onur's Duru uses this and I had been
anticipating re-using his OT code. But until we have small caps the issue
does not come up.

**Comment by davelab6** [comment]
Rainer corrected me on the glyphs forum; it should be this instead, I think

```
language KAZ;
sub f idotless by f_i_trk;
language TAT;
sub f idotless by f_i_trk;
language TRK;
sub f idotless by f_i_trk;
language CRT;
sub f idotless by f_i_trk;
language AZE;
sub f idotless by f_i_trk;

**Comment by EbenSorkin** [comment]
Fixed
