### ISSUE TITLE
Glyph review R04

### ISSUE THREAD

**Issue by m4rc1e** [EbenSorkin/Merriweather#49]
Fix these:

![screen shot 2017-10-30 at 16 08 39](https://user-images.githubusercontent.com/7525512/32181873-56b533fa-bd8d-11e7-8f71-bcd9753d0a24.png)
![screen shot 2017-10-30 at 16 08 01](https://user-images.githubusercontent.com/7525512/32181874-56d3e48a-bd8d-11e7-9ee2-34c66b7f598a.png)
![screen shot 2017-10-30 at 16 07 40](https://user-images.githubusercontent.com/7525512/32181875-5711d51a-bd8d-11e7-8d84-76c2103f6ccf.png)
![screen shot 2017-10-30 at 16 07 27](https://user-images.githubusercontent.com/7525512/32181878-5726deec-bd8d-11e7-912f-a262e2d4ec12.png)
![screen shot 2017-10-30 at 16 06 59](https://user-images.githubusercontent.com/7525512/32181882-57573146-bd8d-11e7-8b86-135aa34462ca.png)
![screen shot 2017-10-30 at 16 06 56](https://user-images.githubusercontent.com/7525512/32181883-576dc0fa-bd8d-11e7-80a8-e28aa291c8d7.png)

Double check these in all weights:
guillemotleft, guillemotright, AE, currency symbols.

Also, your numerals have shifted quite a bit. Was this intentional?

![merriweather-fig](https://user-images.githubusercontent.com/7525512/32181946-7dc0b618-bd8d-11e7-8ff7-3dfedc5a266d.gif)

**Comment by m4rc1e** [comment]
Also, you have outlines missing for uni0528, uni0529. They should look like this:

![screen shot 2017-10-30 at 16 16 35](https://user-images.githubusercontent.com/7525512/32182051-b8ee9fe8-bd8d-11e7-88b2-4d60cb874b77.png)

**Comment by EbenSorkin** [comment]
RE: 0528 and 0529. I see them both in the master files and they don't seem to have trouble interpolating. I also see them in the TTFs. Could it that the system that checks for them wants a name other than for instance "uni0528"?

**Comment by EbenSorkin** [comment]
I have fixed the interpolation errors.
