### ISSUE TITLE
Tag VFB version, remove /old

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#50]
The https://github.com/EbenSorkin/Merriweather/tree/master/old/version-1.584/SRC directory is just hanging around, I suggest to 

- [ ] go to https://github.com/EbenSorkin/Merriweather/releases and tag commit b221ad77cf9d730b32a921b62b62961726b84ea5 as v1.582 and note this was the last version with VFB (and UFO) source files before moving to Glyphs

- [ ] Remove the `/old` directory

**Comment by EbenSorkin** [comment]
This is done and ready to be pushed

**Comment by davelab6** [comment]
I'm don't see it on https://github.com/EbenSorkin/Merriweather/tags
