### ISSUE TITLE
Add /documents sources + README.md

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#51]
@alexeiva please add source files and a `/documents/README.md` that in 1-2 paragraphs explains the source documents and how to build them :) 

https://github.com/EbenSorkin/Merriweather/tree/master/documents

**Comment by alexeiva** [comment]
I've added a basic [readme](https://github.com/alexeiva/Merriweather/tree/patch-1/documents) here. I think a guide for making variable font is required too. I am not aware how @EbenSorkin generated variable fonts.
