### ISSUE TITLE
Complete language support for all 97%+ languages

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/Merriweather#56]
I'd like to request just a few languages which have over 90% character support and are just missing a few characters :)

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| Italian (it) | 108/108 | 100 |  |
| Norwegian (no) | 105/105 | 100 |  |
| Slovenian (sl) | 112/112 | 100 |  |
| Ukrainian (uk) | 98/98 | 100 |  |
| Estonian (et) | 105/105 | 100 |  |
| Swahili (sw) | 39/39 | 100 |  |
| English (en) | 120/121 | 99 | \u2010 (‐) |
| German (de) | 125/126 | 99 | \u2010 (‐) |
| English (United Kingdom) (en-GB) | 120/121 | 99 | \u2010 (‐) |
| Spanish (es) | 129/130 | 99 | \u2010 (‐) |
| Spanish (Latin America) (es-419) | 129/130 | 99 | \u2010 (‐) |
| French (fr) | 112/113 | 99 | \u2010 (‐) |
| Dutch (nl) | 109/110 | 99 | \u2010 (‐) |
| Polish (pl) | 125/126 | 99 | \u2010 (‐) |
| Portuguese (pt) | 123/124 | 99 | \u2010 (‐) |
| Turkish (tr) | 129/130 | 99 | \u2010 (‐) |
| Catalan (ca) | 128/129 | 99 | \u2010 (‐) |
| Czech (cs) | 129/130 | 99 | \u2010 (‐) |
| Danish (da) | 109/110 | 99 | \u2010 (‐) |
| Lithuanian (lt) | 105/106 | 99 | \u2010 (‐) |
| Latvian (lv) | 108/109 | 99 | \u2010 (‐) |
| Portuguese (Portugal) (pt-PT) | 123/124 | 99 | \u2010 (‐) |
| Romanian (ro) | 101/102 | 99 | \u2010 (‐) |
| Slovak (sk) | 130/131 | 99 | \u2010 (‐) |
| Swedish (sv) | 108/109 | 99 | \u2010 (‐) |
| Vietnamese (vi) | 156/157 | 99 | \u2010 (‐) |
| Afrikaans (af) | 107/108 | 99 | \u2010 (‐) |
| Icelandic (is) | 102/103 | 99 | \u2010 (‐) |
| Kazakh (kk) | 114/115 | 99 | \u2010 (‐) |
| Kyrgyz (ky) | 102/103 | 99 | \u2010 (‐) |
| Russian (ru) | 95/96 | 98 | \u2010 (‐) |
| Bulgarian (bg) | 91/92 | 98 | \u2010 (‐) |
| Filipino (fil) | 96/97 | 98 | \u2010 (‐) |
| Croatian (hr) | 88/89 | 98 | \u2010 (‐) |
| Indonesian (id) | 73/74 | 98 | \u2010 (‐) |
| Serbian (sr) | 90/91 | 98 | \u2010 (‐) |
| Azerbaijani (az) | 96/97 | 98 | \u2010 (‐) |
| Macedonian (mk) | 84/85 | 98 | \u2010 (‐) |
| Mongolian (mn) | 69/70 | 98 | \u2010 (‐) |
| Malay (ms) | 82/83 | 98 | \u2010 (‐) |
| Albanian (sq) | 86/87 | 98 | \u2010 (‐) |
| Serbian (Latin) (sr-Latn) | 83/84 | 98 | \u2010 (‐) |
| Hungarian (hu) | 130/133 | 97 | \u2052 (⁒), \u27e8 (⟨), \u27e9 (⟩) |
| Uzbek (uz) | 85/87 | 97 | \u2010 (‐), \u02bb (ʻ) |

**Comment by j-f1** [comment]
Here’s a summary of what’s missing:

- [ ] `U+2010` ‐ <small>HYPHEN</small> (37 languages)
- [ ] `U+2052` ⁒ <small>COMMERCIAL MINUS SIGN</small> (1 language)
- [ ] `U+27E8` ⟨ <small>MATHEMATICAL LEFT ANGLE BRACKET</small> (1 language)
- [ ] `U+27E9` ⟩ <small>MATHEMATICAL RIGHT ANGLE BRACKET</small> (1 language)
- [ ] `U+02BB` ʻ <small>MODIFIER LETTER TURNED COMMA</small> (1 language)

**Comment by EbenSorkin** [comment]
Will do!

**Comment by EbenSorkin** [comment]
Almost done

**Comment by EbenSorkin** [comment]
fixed
