### ISSUE TITLE
Improve Vietnamese

### ISSUE THREAD

**Issue by crystaltype** [EbenSorkin/Merriweather#58]
Only a little mistake: The brevehookabove in Abrevehookabove (in all weights) are misplaced.
Everything else is okay.

![screen shot 11-11-17 at 01 32 pm](https://user-images.githubusercontent.com/20129845/32733438-d4b635bc-c8c1-11e7-971e-d9003ea2565a.PNG)

I'm willing to help contribute the changes directly, by sending you a 'vietnamese only' glyphapp file for you to review and integrate.

Or, you can make changes and then push your work to master and I will give further feedback :)

**Comment by EbenSorkin** [comment]
I am planning on making updates to this so the breve does not contact the A. I think that's what you mean by misplaced. The target I have in mind is a bit like this https://vietnamesetypography.com/type-recommendations/halyard/

Would you comment further?

Thanks!

-e.

**Comment by crystaltype** [comment]
Yes that's exactly what I mean. 

For your target, I think it's not that good. There is some problems with the horn, it's too big, and its shape is weird. Anyway I think Merriweather is all good, only one little small mistake like I said above.

Thanks!

**Comment by EbenSorkin** [comment]
I what references would you point me to to make a better horn shape?

I am glad that the concept itself of scaling the parts that make up the
Vietnamese diacritic mark is one that you agree is the preferred one. That
was the main thing I wanted to clarify before further revising Merriweather
and Merriweather Sans

-e.

**Comment by crystaltype** [comment]
I think this is a good reference material: https://vietnamesetypography.com/diacritical-details/

I would prefer the 1st method while designing the horn in the article, as the 2nd method will sometimes make it more complicated as you have to change the width of uhorn/ohorn to avoid overlapping the followed character.

In general, I would recommend stick to these guidelines while designing a horn:
- Make sure that the horn matches the overall style of the font. 
- It should be at the same weight as the stem weight. Also its height should be no more than 1/3 of the x-height.
- In the slab/serif fonts, the serif on the right of Uhorn should be replaced by the horn, not attaching it to the serif.
- These kerning pairs should be paid attention to: 
ưn ơn ưt ơt ưp ơp ươ ưa ưc ươc ưi ơi ưm ơm (and also their uppercase counterparts).
These pairs are only the one that appears in Vietnamese.
- In general, the horn in both u and o should always be at the same height.

These are the most important things I think of when designing the horn. There is more to it but I think it is more or less will affect the overall design of the font, so if we want a perfect Vietnamese font, there are a lot to consider, especially when on the early stage of the font design process. For now I think this is enough for a good Vietnamese font that everyone can accept.

**Comment by EbenSorkin** [comment]
thank you!

**Comment by EbenSorkin** [comment]
Fixed
