### ISSUE TITLE
Bitcoin sign support (U+20BF)

### ISSUE THREAD

**Issue by fitojb** [EbenSorkin/Merriweather#59]
Hi, would it be possible to add the bitcoin sign that was encoded in Unicode 10.0? Thanks for considering!

**Comment by EbenSorkin** [comment]
I see. It is U+20BF.

Yes I will.

-e.

**Comment by EbenSorkin** [comment]
I have fixed this for the Roman as of today and will do the same for Italic tomorrow.

**Comment by EbenSorkin** [comment]
fixed
