### ISSUE TITLE
Merriweather quotedblright.ss01 smashes together

### ISSUE THREAD

**Issue by laerm0** [EbenSorkin/Merriweather#60]
The two components in the regular, black, and bold, weights are too close together.

(identical to https://github.com/google/fonts/issues/1331)

**Comment by laerm0** [comment]
![screen region 2017-11-16 at 14 43 28](https://user-images.githubusercontent.com/10780161/32912289-91730fe2-cadc-11e7-84dd-d10aadf61fb8.png)

**Comment by EbenSorkin** [comment]
This is fixed in the sources now and will be merged in along with other fixes soon.

**Comment by EbenSorkin** [comment]
fixed
