### ISSUE TITLE
Add 1/5 fraction.

### ISSUE THREAD

**Issue by inferno986return** [EbenSorkin/Merriweather#61]
I have gotten into using Merriweather as typeface for recipes and it works pretty well so far. However ⅕ does not seem to have its own glyph. Can I request it be added in, alongside a few other fractions listed here (http://unicodefractions.com/)? :-)

**Comment by EbenSorkin** [comment]
Yes. It looks like any and all arbitrary fractions will be supported as
opentype features. You could make 345/786 for instance. But is there a
separate case to be made for precomposed fractions to be included too?
Maybe there is. What's your view?

-e.

**Comment by inferno986return** [comment]
I think most of the common fractions should be supported as standard. As we all work in base-10 ordinarily, I think it would be best to support the fractions from 1 to 10 at least. :-)

**Comment by EbenSorkin** [comment]
I don't follow what you mean by "fractions from 1 to 10 at least. " would
you give me an example?

I think that the unicode encoded one seem like they might be enough.
Probably if you need a fraction that is unlikely but possible e.g. 2/4
which is better put as 1/2 or 7/10 it makes sense to use the open type
feature made to support any kind of arbitrary fraction you might care to
invent.

I will have a look at what unicode provides for and see if my idea about
this holds.

**Comment by inferno986return** [comment]
I was referring to the list on that site I listed called appropriately UnicodeFractions.com.

With every numerator and denominator supported natively from ½ to ⅒. Of course if there's a way to dynamically support any fraction, that would be an awesome bonus.

**Comment by EbenSorkin** [comment]
Done!
