### ISSUE TITLE
Missing spaces

### ISSUE THREAD

**Issue by vincentbernat** [EbenSorkin/Merriweather#62]
Hey!

Merriweather is missing some space characters in the U+2000-U+200A range. For example, U+2003 is absent, U+202F is absent. Last one can be produced with &nnbsp; and be used before a double punctuation in French. In web browsers, the rendering depends on the fallback font.

I have first reported the issue in Google Fonts are some spaces are present in Merriweather but not provided in the font distributed by Google: https://github.com/google/fonts/issues/1395.

**Comment by EbenSorkin** [comment]
I'll be working this today then. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EbenSorkin** [comment]
I fixed these today in the roman. I'll do the Italic tommrow.

**Comment by EbenSorkin** [comment]
Fixed
