### ISSUE TITLE
Add support for Skolt Sami?

### ISSUE THREAD

**Issue by AshtarBalynestjar** [EbenSorkin/Merriweather#63]
Ezh (capital U+01B7 Ʒ, small U+0292 ʒ) is not encoded, but the glyph from Abkhazian Dze is the same.

Six letters can take a caron: č ǯ ǧ ǩ š ž. Four of them (č ǧ š ž) are already encoded, and capital Ǩ is rendered correctly on my end. The caron on the small ǩ in the roman, however, is somehow rendered on the baseline, to the left of the k and partially overlapping with it. In the italic, the caron is correctly positioned on top of the letter, but there’s still some overlap. (see attached pdf)

Finally, there’s G with stroke (capital U+01E4 Ǥ, small U+01E5 ǥ). This letter can have several different glyphs depending on the language, but in Sami, the stroke goes through the stem of the capital G and through the loop of the small g.

[ǩ.pdf](https://github.com/EbenSorkin/Merriweather/files/1662646/default.pdf)

**Comment by EbenSorkin** [comment]
Thanks for this detailed review and request. I'll advocate for adding it to the next release!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AshtarBalynestjar** [comment]
When should we be expecting the next release? Just a rough estimate...

**Comment by EbenSorkin** [comment]
Ideally before the end of the first quarter of the year. But the schedule depends on google.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by EbenSorkin** [comment]
Done
