### ISSUE TITLE
Quotes in stylistic set 01 

### ISSUE THREAD

**Issue by AshtarBalynestjar** [EbenSorkin/Merriweather#64]
I’m not entirely sure what the issue is here.

I’m not sure if this is a bug or a feature, but in all 8 styles, the opening single quotes point down rather than up, looking like the character U+201B. Is this what Gawker intended? In that case, you should probably advise them to use that character instead of the U+2018 that the glyph is currently encoded at. 

Also, the closing double quotes are too close together in the roman regular and black, and in the bold, they’re almost completely overlapping. This doesn’t happen in the italic, so I’m not sure what’s going on.

![screenshot from 2018-02-19 10-39-43](https://user-images.githubusercontent.com/30967003/36391214-d4eb46ec-1562-11e8-8867-3d534f50af2d.png)

**Comment by EbenSorkin** [comment]
No, this was an interpolation bug. I have fixed it now and it along with
quotes with improved shapes will be available in the next edition.
