### ISSUE TITLE
Lowercase eth

### ISSUE THREAD

**Issue by AshtarBalynestjar** [EbenSorkin/Merriweather#65]
The crossbar on the lowercase eth in Merriweather looks a little weird. It’s too steep and too high up on the ascender, so much that its highest point goes beyond the body of the letter by a considerable amount. 

You might want to look at [this guide](http://www.briem.net/2/2.11/2.1.4.eth.htm) on Gunnlaugur Briem’s site.

**Comment by EbenSorkin** [comment]
I'll have to look at this again. The angle of the cross bar was chosen to be compatible with low rez devices with little or no hinting. But with higher rez a different approach could be taken now. Thanks!

**Comment by EbenSorkin** [comment]
Ok fixed. Hopefully you will see it here soon.

**Comment by AshtarBalynestjar** [comment]
The stroke is still too high up, I think. The angle is significantly better, but it should probably be located about halfway up the ascender instead.
