### ISSUE TITLE
Numerals?

### ISSUE THREAD

**Issue by AshtarBalynestjar** [EbenSorkin/Merriweather#66]
The main gap in Merriweather as it stands right now appears to be superscript and subscript numerals.

The characters ¹ ² ³ ⁴ are encoded, and they’re assigned to the `sups` feature, so that’s good. The rest of the superscript digits are missing, though. 

The `subs` and `sinf` features affect the digits 1 2 3 4 5 7, but those glyphs aren’t assigned to the Unicode codepoints for subscript digits.

The digits 0 6 8 9 are missing from the numerator set, and the denominators are missing 0 1 5 6 7 9.

Fortunately, this should be easy to fix.

**Comment by AshtarBalynestjar** [comment]
Also on this topic, some European languages use superscript letters that aren’t in Unicode, but they’re the established practice for typesetting ordinal numbers and some abbreviations. The OpenType feature `ordn` was designed for this. 

The glyphs encoded at U+00BA º and U+00AA ª are the most common, but Spanish also uses superscript “er”, “as” and “os”, and English, of course, needs “st”, “nd”, “rd” and “th”, for example.

**Comment by EbenSorkin** [comment]
All the small numbers are now in Merriweather. This needs to be pushed live after some tests are done. But they are now there. Unicodes should be automatic with the gLyphs sources.

I'll need to discuss with Google if they care about ordinal letters. They might. The thing is in english at least it is increasingly culturally uncommon to treat the “st”, “nd”, “rd” and “th”, with ordinals. Where as I don't think this is so for Spanish and we do already have Spanish support.

**Comment by EbenSorkin** [comment]
Interesting! I would love to add IPA to Merriweather.

-e.

**Comment by AshtarBalynestjar** [comment]
I’ve actually been writing an email in my spare time about how to design the letters of the IPA, and what glyphs need special attention. It’ll probably be done today or tomorrow I think.

**Comment by EbenSorkin** [comment]
I'd love to see it


On Fri, Apr 13, 2018 at 1:57 PM, AshtarBalynestjar <notifications@github.com

**Comment by EbenSorkin** [comment]
Also, what do you know about support for African languages? There is some overlap with IPA.

**Comment by EbenSorkin** [comment]
Small numbers fixed
