### ISSUE TITLE
Small Caps?

### ISSUE THREAD

**Issue by RGB-es** [EbenSorkin/Merriweather#70]
Do you have any plan to add Small Caps to Merryweather? Thanks!

**Comment by inferno986return** [comment]
I too would like the formal addition of small caps.

**Comment by db-inf** [comment]
The author offers to make this happen on his [support page](https://ebensorkin.wordpress.com/support-merriweather/)

**Comment by alecgibson** [comment]
In v2.004 (2 Feb 2019):

> Created initial version of small caps for Roman and Italic in the sources. However they don't currently export because they are a) not done and b) have no kerning. Small caps are made for Latin, Cyrillic, Greek Symbols and Figures. Small caps are using comb diacritics. Small cap punctuation and currency could be added - I am not sure if I think this make sense or not yet. Notes: - I also don't yet understand what the best design approach to small caps for digraphs including DZ, DZcaron, Dz, Dzcaron, NJ, Nj, is. - The final remix RMX Scaller settings used to make the small caps were Width 96, Height 87 Weight 2 and 1 and adjust spacing 2.

We'd love to see the addition of small caps, too 😀

**Comment by EbenSorkin** [comment]
Small caps are VERY close to coming now. They are made but not adjusted for color or kerned yet.

**Comment by EbenSorkin** [comment]
Small caps are now in this version: https://github.com/SorkinType/Merriweather
