### ISSUE TITLE
Missing Glyphs from master Glyphs App file

### ISSUE THREAD

**Issue by brandon-knap** [EbenSorkin/Merriweather#71]
The master glyphs file is missing the all Punctuation, Symbols, most Numbers, Marks, and Separators, and Other section.
I am running on Glyphs Version 2.5.1 (1141). Italics master seems error free.

<img width="1440" alt="screen shot 2018-12-17 at 4 34 36 pm" src="https://user-images.githubusercontent.com/7365341/50117062-eae7ab80-0219-11e9-807d-c08370f5fd18.png">
<img width="1440" alt="screen shot 2018-12-17 at 4 34 22 pm" src="https://user-images.githubusercontent.com/7365341/50117074-f3d87d00-0219-11e9-95aa-0cdb61035105.png">
<img width="1149" alt="screen shot 2018-12-17 at 4 37 21 pm" src="https://user-images.githubusercontent.com/7365341/50117119-0fdc1e80-021a-11e9-8f7d-af108568af3c.png">

**Comment by EbenSorkin** [comment]
Oddest thing!

I think I can push an update to Git today.

-e.

**Comment by brandon-knap** [comment]
That would be great! I can't wait to get under the hood of this thing.

**Comment by brandon-knap** [comment]
Our company, CQL, is rebranding and we are planning on pairing it with a custom version of the font I designed, [Clarika](https://clarika.refinery.design/). There are things I would like to do with it such as match x-heights of the two fonts and perhaps tweak the instances if we need to do some weight matching between the two fonts. For usability, I am considering rolling it out named as CQL Merriweather and CQL Clarika purely for our company to create branded content.

Are you okay if we do this? Perhaps we will find improvements for the font along the way we could add to the base project.

**Comment by brandon-knap** [comment]
@EbenSorkin I am wondering if you have had a chance to take a look at this issue pertaining to the missing glyphs in the project files.

**Comment by EbenSorkin** [comment]
I have been fighting a (still) unknown kerning issue in a different project and lost track of this. I'll see about pushing the latest file into sources now.

**Comment by EbenSorkin** [comment]
Updated.

**Comment by brandon-knap** [comment]
Excellent, everything appears to be in order. Thank you for taking a look at this!
