### ISSUE TITLE
Cap-height numerals?

### ISSUE THREAD

**Issue by inferno986return** [EbenSorkin/Merriweather#72]
I would like to request cap-height numerals that are compatible with `font-variant-numeric: proportional-nums;` as documented on Mozilla: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric

For example the original Georgia used text-figures, yet the Georgia Pro release had cap-height numerals. It would be great to consider them as stylistic alternatives.

![screenshot_2019-01-28_11-40-45](https://user-images.githubusercontent.com/1838420/51834252-aa3b8180-22f1-11e9-9858-92a594dfba70.png)

**Comment by EbenSorkin** [comment]
These have been added in the newest version. They should be part of the official version use din the Google font service soon.
