### ISSUE TITLE
Ezh

### ISSUE THREAD

**Issue by AshtarBalynestjar** [EbenSorkin/Merriweather#75]
I’d like to report a few issues regarding the letter ezh.

First, the glyph for the italic lowercase ezh seems fairly weak. The top stroke is currently flat, unlike the thicker convex one on the lowercase z, and the descender is shorter and thinner than any others currently found in the font. The italic capital ezh seems fine, though.

Second, only the roman lowercase ezh actually has an anchor point for a diacritic. Ezh with caron is encoded as a precomposed character in Unicode (capital U+01EE, lowercase U+01FF), and is used in Skolt Sami.
![image](https://user-images.githubusercontent.com/30967003/52766151-7778d500-2fe3-11e9-9604-ebd2ba9605d3.png)

**Comment by EbenSorkin** [comment]
Thanks for finding these bugs. I'll change this tonight!

-e.

**Comment by AshtarBalynestjar** [comment]
I just realized the serif on top of the capital ezh is also inconsistent with Z. I’m not sure if this was a design decision though, since it seems to work well by itself.

**Comment by EbenSorkin** [comment]
I'll check if they are meant to match or not.

BTW both Merriweather and Merriweather Sans have the ezh and ezh caron glyphs
now. I am working to publish the fonts themselves today.

**Comment by EbenSorkin** [comment]
I have added them. I should be replacing the TTFs and OTFs this weekend.

**Comment by AshtarBalynestjar** [comment]
The descender on the italic ezh still looks a bit too short, and I think it should probably have a wider terminal like the one on the italic g.
