### ISSUE TITLE
Circumflex-acute does not render properly

### ISSUE THREAD

**Issue by AshtarBalynestjar** [EbenSorkin/Merriweather#76]
The circumflex in the lowercase letters ế ấ ố seems to be broken in the roman.

![image](https://user-images.githubusercontent.com/30967003/52841306-30f5aa00-30b9-11e9-8982-2b95112f1735.png)

**Comment by AshtarBalynestjar** [comment]
Update: The circumflex-hook and circumflex-tilde combinations on capital letters also seem to be affected. 
![image](https://user-images.githubusercontent.com/30967003/52841551-d7da4600-30b9-11e9-94bf-e6f0083e01e2.png)

**Comment by EbenSorkin** [comment]
Fixing this now. Thanks again!

-e.
