### ISSUE TITLE
Capital sharp s

### ISSUE THREAD

**Issue by bardware** [EbenSorkin/Merriweather#9]
Hi,

German language has the strange character `sharp s` that is typically used as last character in a word and thus not needed as capital character. However, some times ago an uppercase variant `became mandatory in official documentation when writing geographical names in all-caps` as [Wikipedia](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E) states. 
Will you maybe add it to your font?

Best,
Bernhard

**Comment by EbenSorkin** [comment]
It has been added to the version on Font Squirrel. I am a supporter of the letter. 

If you go here: 

http://www.fontsquirrel.com/fonts/merriweather

And look at the glyph set - near the bottom next to the Y + diacritics it is there.

Is that useful for your purposes?

I hope that Google will update Merriweather soon.

-e.

**Comment by bardware** [comment]
perfect, thanks.

**Comment by davelab6** [comment]
@bardware This should now be fixed in the version on Google Fonts. Please confirm :)

**Comment by bardware** [comment]
nice, thanks alot
